apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    helm.sh/hook-weight: "300"
spec:
  license:
    {{- toYaml .Values.license | nindent 4 }}
  queueManager:
    {{- toYaml .Values.queuemanager | nindent 4 }}
  version: {{ .Values.version }}
