apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: nativeha-example
spec:
  license:
    accept: true
    license: L-RJON-BYRMYW
    use: NonProduction
  queueManager:
    availability:
      type: NativeHA
  version: 9.2.2.0-r1
